name: continuous-integration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v4
    - run: mdbook build
    - uses: actions/upload-artifact@v4
      with:
        name: book
        path: ./target/book
  upload-book:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: book
          path: ./target/book
      - uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/book