name: Book
on:
  push:
    branches:
      - main
jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v4
    - run: mdbook build
    - uses: actions/upload-artifact@v4
      with:
        name: book
        path: ./target/book
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/book
